spring:
  application:
    name: service-order
    instance_id: i0
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 5000
        max-attempts: 10
        max-interval: 5000
        multiplier: 1.2
  config:
    import: optional:configserver:http://host.docker.internal:8888
  codec:
    max-in-memory-size: 10MB

eureka:
  client:
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://host.docker.internal:9999/eureka/
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: service-order:${spring.application.instance_id:0}
    lease-renewal-interval-in-seconds: 30
    metadataMap:
      zone: zone1
management:
  zipkin:
    tracing:
      endpoint: "http://host.docker.internal:9411/api/v2/spans"
